// TODO: MIGRATE TO XENO-RT — this module belongs in the inference runtime, not the processing library.
// All ONNX Runtime inference (model loading, triplane inference, volume generation) should move
// to xeno-rt. The Vertex, Triangle, GeneratedMesh structs and OBJ/STL export functions are pure
// geometry/I/O and STAY in xeno-lib. The marching cubes algorithm (if implemented) is pure
// processing and STAYS.
//!
//! AI-powered text/image to 3D mesh generation.
//!
//! This module converts 2D images into 3D triangle meshes using deep learning models.
//! Supports TripoSR (fast), InstantMesh (quality), and Wonder3D (multi-view).
//!
//! # Architecture
//!
//! The pipeline follows: Image -> Preprocess -> ONNX Inference -> Volume -> Marching Cubes -> Mesh
//!
//! # Model Research (2025-2026)
//!
//! - **TripoSR** by StabilityAI/Tripo: fastest single-image-to-3D, ~0.5s on GPU.
//!   Based on transformer architecture, outputs triplane features.
//!   ONNX export available via torch.onnx.export.
//! - **InstantMesh** by TencentARC: multi-view reconstruction with better topology.
//!   Uses sparse-view reconstruction, ~2s on GPU. ONNX partially supported.
//! - **Wonder3D** by xxlong0: multi-view diffusion, highest quality but ~10s.
//!   ONNX support experimental, kept as future integration stub.
//!
//! # Output Contract
//!
//! All mesh outputs use the `GeneratedMesh` struct with:
//! - Vertices: `[f32; 3]` positions in normalized [-1, 1] space
//! - Normals: `[f32; 3]` unit normals
//! - UVs: `[f32; 2]` texture coordinates in [0, 1]
//! - Triangles: `[u32; 3]` vertex index triplets
//!
//! # Quick Start
//!
//! ```rust,no_run
//! use xeno_lib::text_to_3d::{generate_3d, load_mesh_model, Mesh3DConfig};
//!
//! let config = Mesh3DConfig::default();
//! let mut session = load_mesh_model(&config)?;
//! let input = image::open("object.png")?;
//! let mesh = generate_3d(&input, &mut session)?;
//! println!("Generated {} vertices, {} triangles", mesh.vertices.len(), mesh.triangles.len());
//! mesh.export_obj("output.obj")?;
//! # Ok::<(), Box<dyn std::error::Error>>(())
//! ```

pub mod config;
pub mod model;
pub mod processor;

use image::DynamicImage;
use std::io::Write;
use std::path::Path;

pub use config::{Mesh3DConfig, Mesh3DModel, MeshFormat};
pub use model::{load_mesh_model, Mesh3DSession};

use crate::error::TransformError;

/// A 3D vertex with position, normal, and UV coordinates.
#[derive(Debug, Clone, Copy)]
pub struct Vertex {
    /// 3D position [x, y, z] in normalized space.
    pub position: [f32; 3],
    /// Surface normal [nx, ny, nz], unit length.
    pub normal: [f32; 3],
    /// Texture coordinate [u, v] in [0, 1].
    pub uv: [f32; 2],
}

/// A triangle defined by three vertex indices.
#[derive(Debug, Clone, Copy)]
pub struct Triangle {
    /// Indices into the vertex array.
    pub indices: [u32; 3],
}

/// A generated 3D mesh.
#[derive(Debug, Clone)]
pub struct GeneratedMesh {
    /// Mesh vertices.
    pub vertices: Vec<Vertex>,
    /// Mesh triangles.
    pub triangles: Vec<Triangle>,
    /// Whether UVs are present.
    pub has_uvs: bool,
    /// Whether normals are present.
    pub has_normals: bool,
}

impl GeneratedMesh {
    /// Returns the number of vertices.
    pub fn vertex_count(&self) -> usize {
        self.vertices.len()
    }

    /// Returns the number of triangles.
    pub fn triangle_count(&self) -> usize {
        self.triangles.len()
    }

    /// Exports to OBJ format string.
    pub fn to_obj_string(&self) -> String {
        let mut obj = String::new();
        obj.push_str("# Generated by xeno-lib\n");

        // Vertices
        for v in &self.vertices {
            obj.push_str(&format!(
                "v {} {} {}\n",
                v.position[0], v.position[1], v.position[2]
            ));
        }

        // Normals
        if self.has_normals {
            for v in &self.vertices {
                obj.push_str(&format!(
                    "vn {} {} {}\n",
                    v.normal[0], v.normal[1], v.normal[2]
                ));
            }
        }

        // UVs
        if self.has_uvs {
            for v in &self.vertices {
                obj.push_str(&format!("vt {} {}\n", v.uv[0], v.uv[1]));
            }
        }

        // Faces (OBJ indices are 1-based)
        for t in &self.triangles {
            let i0 = t.indices[0] + 1;
            let i1 = t.indices[1] + 1;
            let i2 = t.indices[2] + 1;

            if self.has_normals && self.has_uvs {
                obj.push_str(&format!(
                    "f {}/{}/{} {}/{}/{} {}/{}/{}\n",
                    i0, i0, i0, i1, i1, i1, i2, i2, i2
                ));
            } else if self.has_normals {
                obj.push_str(&format!(
                    "f {}//{} {}//{} {}//{}\n",
                    i0, i0, i1, i1, i2, i2
                ));
            } else {
                obj.push_str(&format!("f {} {} {}\n", i0, i1, i2));
            }
        }

        obj
    }

    /// Exports mesh to an OBJ file.
    pub fn export_obj<P: AsRef<Path>>(&self, path: P) -> Result<(), TransformError> {
        let content = self.to_obj_string();
        let mut file = std::fs::File::create(path.as_ref())?;
        file.write_all(content.as_bytes())?;
        Ok(())
    }

    /// Exports mesh to STL binary format.
    pub fn export_stl<P: AsRef<Path>>(&self, path: P) -> Result<(), TransformError> {
        let mut file = std::fs::File::create(path.as_ref())?;

        // STL header (80 bytes)
        let header = [0u8; 80];
        file.write_all(&header)?;

        // Number of triangles
        let num_triangles = self.triangles.len() as u32;
        file.write_all(&num_triangles.to_le_bytes())?;

        // Write each triangle
        for tri in &self.triangles {
            let i0 = tri.indices[0] as usize;
            let i1 = tri.indices[1] as usize;
            let i2 = tri.indices[2] as usize;

            if i0 >= self.vertices.len() || i1 >= self.vertices.len() || i2 >= self.vertices.len() {
                continue;
            }

            // Normal (use first vertex normal)
            let n = self.vertices[i0].normal;
            for &val in &n {
                file.write_all(&val.to_le_bytes())?;
            }

            // Three vertices
            for &idx in &tri.indices {
                let v = &self.vertices[idx as usize];
                for &val in &v.position {
                    file.write_all(&val.to_le_bytes())?;
                }
            }

            // Attribute byte count
            file.write_all(&0u16.to_le_bytes())?;
        }

        Ok(())
    }
}

/// Generates a 3D mesh from an input image.
///
/// # Arguments
///
/// * `image` - Input image containing the object to reconstruct.
/// * `session` - A loaded 3D generation model session.
///
/// # Returns
///
/// A `GeneratedMesh` with vertices, normals, UVs, and triangle indices.
pub fn generate_3d(
    image: &DynamicImage,
    session: &mut Mesh3DSession,
) -> Result<GeneratedMesh, TransformError> {
    processor::generate_mesh(image, session)
}

/// Quick 3D generation that loads model and processes in one call.
pub fn generate_3d_quick(
    image: &DynamicImage,
    model: Mesh3DModel,
) -> Result<GeneratedMesh, TransformError> {
    let config = Mesh3DConfig::new(model);
    let mut session = load_mesh_model(&config)?;
    generate_3d(image, &mut session)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_empty_mesh() {
        let mesh = GeneratedMesh {
            vertices: vec![],
            triangles: vec![],
            has_uvs: true,
            has_normals: true,
        };
        assert_eq!(mesh.vertex_count(), 0);
        assert_eq!(mesh.triangle_count(), 0);
    }

    #[test]
    fn test_obj_export_string() {
        let mesh = GeneratedMesh {
            vertices: vec![
                Vertex { position: [0.0, 0.0, 0.0], normal: [0.0, 1.0, 0.0], uv: [0.0, 0.0] },
                Vertex { position: [1.0, 0.0, 0.0], normal: [0.0, 1.0, 0.0], uv: [1.0, 0.0] },
                Vertex { position: [0.0, 0.0, 1.0], normal: [0.0, 1.0, 0.0], uv: [0.0, 1.0] },
            ],
            triangles: vec![Triangle { indices: [0, 1, 2] }],
            has_uvs: true,
            has_normals: true,
        };

        let obj = mesh.to_obj_string();
        assert!(obj.contains("v 0 0 0"));
        assert!(obj.contains("vn 0 1 0"));
        assert!(obj.contains("vt 0 0"));
        assert!(obj.contains("f 1/1/1 2/2/2 3/3/3"));
    }

    #[test]
    fn test_mesh_format_default() {
        assert_eq!(Mesh3DConfig::default().output_format, MeshFormat::Obj);
    }
}
